services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "9002:8080"
    volumes:
      - open-webui:/app/backend/data
    restart: always

  mcpo-server:
    build: .
    container_name: mcpo-server
    ports:
      - "9003:8000"
    environment:
      GITHUB_PAT: ${GITHUB_PAT}
      MCPO_API_KEY: ${MCPO_API_KEY}
      GITEA_HOST: ${GITEA_HOST}
      GITEA_ACCESS_TOKEN: ${GITEA_ACCESS_TOKEN}
    restart: unless-stopped


volumes:
  open-webui:
