[project]
name = "audio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "mlx-audio>=0.3.1",
    "python-multipart>=0.0.22",
    "soundfile>=0.13.1",
    "uvicorn>=0.40.0",
]
